# Generated by Django 4.2.1 on 2023-05-18 04:47

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255, verbose_name='Cource')),
                ('trainer', models.CharField(max_length=255, verbose_name='Trainer')),
                ('state_date', models.DateTimeField(null=True, verbose_name='Starte Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('address1', models.CharField(blank=True, max_length=255, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='Address 2')),
                ('address3', models.CharField(blank=True, max_length=255, verbose_name='Address 3')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='Website')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Logo')),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_name', models.CharField(max_length=255, verbose_name='Cource Name')),
            ],
            options={
                'verbose_name_plural': 'Cource',
            },
        ),
        migrations.CreateModel(
            name='EnquirySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquirysourcename', models.CharField(max_length=255, verbose_name='Enquiry Source Name')),
            ],
            options={
                'verbose_name_plural': 'Enquiry Source',
            },
        ),
        migrations.CreateModel(
            name='Followupstatusname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followupstatusname', models.CharField(max_length=255, verbose_name='Folloup Status Name')),
                ('Followupstatus', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Followup Status')),
            ],
            options={
                'verbose_name_plural': 'Followup status name',
            },
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Master Data',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationName', models.CharField(max_length=255, verbose_name='Qualification Name')),
            ],
            options={
                'verbose_name_plural': 'Qualification',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=255, verbose_name='State Name')),
            ],
            options={
                'verbose_name_plural': 'State',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtname', models.CharField(max_length=255, unique=True, verbose_name='District Name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.state', verbose_name='State')),
            ],
            options={
                'verbose_name_plural': 'District',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('branch_code', models.CharField(max_length=255, verbose_name='Branch Code')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adress')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('pincode', models.CharField(blank=True, max_length=6, verbose_name='Pincode')),
                ('mobile_number', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='Employee_app.district', verbose_name='District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.state', verbose_name='State')),
            ],
            options={
                'verbose_name_plural': 'Branch',
            },
        ),
    ]
