# Generated by Django 4.2.1 on 2023-05-19 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='cource_code',
            field=models.CharField(default=1, max_length=20, verbose_name='Cource Code:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cource',
            name='trainers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cource',
            name='cource_name',
            field=models.CharField(max_length=255, verbose_name='Cource:'),
        ),
    ]
