# Generated by Django 4.2.1 on 2023-05-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Employee_app', '0002_cource_cource_code_cource_trainers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cource',
            name='trainers',
        ),
        migrations.AddField(
            model_name='cource',
            name='trainers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
