# Generated by Django 4.2.1 on 2023-05-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_delete_student'),
        ('Employee_app', '0006_alter_cource_trainers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batches',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='district',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='cource',
            name='trainers',
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.DeleteModel(
            name='EnquirySource',
        ),
        migrations.DeleteModel(
            name='Followupstatusname',
        ),
        migrations.DeleteModel(
            name='MasterData',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Cource',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
