# Generated by Django 4.2.1 on 2023-05-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0009_alter_cource_trainers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batches',
        ),
    ]
