# Generated by Django 4.2.1 on 2023-05-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0011_alter_cource_cource_name_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cource',
            name='trainers',
        ),
    ]
