# Generated by Django 4.2.1 on 2023-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0020_alter_batch_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
