# Generated by Django 4.2.1 on 2023-05-21 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee_app', '0022_course_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'faculty', 'is_active': True}, related_name='UserTrainers', to=settings.AUTH_USER_MODEL),
        ),
    ]
