# Generated by Django 4.2.1 on 2023-05-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0027_alter_course_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainers',
        ),
    ]
